name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        short_tags: false
        bump_each_commit: true  # Esto garantiza que el número de versión siempre suba
      id: version
    
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        # Definimos el nombre de la imagen usando tu secreto de usuario
        # y el nombre del repositorio "docker-graphql"
        IMAGE_NAME="${{ secrets.DOCKER_USER }}/docker-graphql"

        echo "Haciendo build de la versión: $NEW_VERSION"

        # Construimos la imagen con dos etiquetas (tags)
        docker build -t $IMAGE_NAME:$NEW_VERSION .
        docker build -t $IMAGE_NAME:latest .
        
        # Subimos ambas etiquetas a Docker Hub
        docker push $IMAGE_NAME:$NEW_VERSION
        docker push $IMAGE_NAME:latest
